name: Reset Server Repo (Manual)

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest

    steps:
      - name: Reset repo on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          script: |
            cd /root/reporeply
            git reset --hard HEAD
            echo "Repository reset completed"
